### ISSUE TITLE
Hubitat basic rule with GT125

### ISSUE THREAD

**Issue by Hubitat4me** [claudegel/Hubitat-sinope-GT125#2]
From the device menu, I can control my thermostats within C7. But when I try to create a basic rule, I receive an error. Is it something that can't be done with the driver?

Unexpected Error
An unexpected error has occurred trying to load the app. Check [Logs](http://192.168.1.28/logs) for more information.

Error: The JSON input text should neither be null nor empty.

LOG: 2022-12-26 17:39:11.699[error](http://192.168.1.28/logs?tab=past&deviceId=45#)java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty. on line 1182 (method mainPage)

**Comment by rfg81** [comment]
It seems related to Hubitat basic rule. I tried with other drivers and got the same problem. Please contact them for support.

**Comment by rfg81** [comment]
I fixed the problem with the driver. In the end a change in the hubitat firmware caused the problem. If you grab latest the problem should be fixed.

**Comment by Hubitat4me** [comment]
Update fixed my issue as well.

thx

**Comment by af0rtin** [comment]
I can create thermostats. I can only access HVAC mode 0 and mode 3. Since I only use Hubitat for load shedding, I would like to Alternate between auto and frost protection. I.E. if generator load > 15 kw start timer 1 else stop timer 1.if generator load < 15 kw stop timer 1.   If timer 1 exceed 30 seconds then all thermostat set to frost protection and start timer 2.  If timer 2 exceed 30 minutes then set all thermostats to auto, reset timer 2
Generator load, timers would be variable and not hardcoded.

I was a to create "THERMOSTAT" foe the RM3250RF. However I cannot get it to turn on of off with any selection from Hubitat.

I measure the power with a Neurio.
Can you point me in the correct direction.
Thank You
